### PR TITLE
Rv3.x

### PR DESCRIPTION
**Pull request by josephwb**
This reduces the version of R required to install `dispRity`, and replaces a conditional check which will work in either R 3.x or 4.x.

See the commit messages for further information.

No worries if you'd rather not accept this PR. But as I point out in the [issue](https://github.com/TGuillerme/dispRity/issues/107) no other phylo package seems to require such a new version of R.

### CODE REVIEW

**Comment by josephwb** [comment]
Hrm not sure why travis checks failed. I'll look into it.

**Comment by josephwb** [comment]
Ah ok the class test condition changed in `sanitizing.R` also occurs in test files. Will update the PR.

**Comment by josephwb** [comment]
Ok so updating the class check condition broke 2 tests. I'm afraid I do not know what you'd prefer these tests to be refactored to, so I left them commented out.

**Comment by TGuillerme** [comment]
Thanks a lot for the fixes @josephwb ! Unfortunately they did not compile on my machine:
 
* Rv3.5.1 did not pass my internal CRAN checks (now updated to Rv3.6)
* The two removed tests were actually important (though your fix removes one warning)

However, I followed your [fix](https://github.com/TGuillerme/dispRity/pull/108/commits/bba83309dbc892ee81e37e218ee0f541ef4295d0) and updated from there. The new version credits you in [`NEWS.md`](https://github.com/TGuillerme/dispRity/blob/master/NEWS.md).

Thanks a lot for figuring that one out!

**Pull request closed without merging**
